### ISSUE TITLE
How to integrate/build on Binder

### ISSUE THREAD

**Issue by nuest** [codecheckers/binderhub#1]
## Ideas

- Maybe we can call a `docker exec` via a new API endpoint in BinderHub? The exec would execute a binary (to be implemented) that reads a `codecheck.yml` (finds the files to check), does the check, and then saves the result (with a "signature") back to the `codecheck.yml` (adding to potentially existing checks). We would manipulate the user container/pod from the outside... and since we would not tell the user about the pod, they also cannot manipulate it. But it would be exactly the same environment they have (i.e. a JupyterHub session/container) that they get when they start the binder for interactive use. We would run the analysis actually in a pod, and not hacked into the r2d build process. Since BinderHub started the JupyterHub, we (should) know the pod and container, so we can also save the container (hopefully) to a file.
- [ ] [papermill](https://github.com/nteract/papermill) allows to execute notebooks via a CLI (and analogously possible with `rmarkdown` in R)
- [ ] We need a small example (e.g. a Python script that generates random numbers based on a seed and a preliminary "check").
- Nothing BinderHub, but enhance JupyterHub with Jupyter extension, see ideas/discussion at https://github.com/jupyterhub/binderhub/issues/579 and https://github.com/jupyterhub/binderhub/issues/674

------

## Questions

- _How does a user "explore" the result of a check?_
- _Do we need JupyterHub?_
  - https://github.com/pangeo-data/pangeo-stacks/pull/10 adds a verify script which now is called as part of [`build.py`](https://github.com/pangeo-data/pangeo-stacks/blob/master/build.py#L77), but that's more to verify the image works OK, not to actually run the analysis... BUT `docker run -i -t ${IMAGE_NAME} "binder/verify"` seems like something that we also want to run. JupyterHub API: https://jupyterhub.readthedocs.io/en/stable/api/
- ~~_Can we assume a check happens automatically after a binder is started, or is it triggered (potentially allowing manipulation of content) manually?_ > Should start right after successful build and launch of the pod/container (?) by JupyterHub ?!~~ checks are "manual", CodecheckersHub only supports that process.
- _Do we need a special UI?_
  - Instead of getting the notebook, you just get a UI that runs the code configured in `codecheck.yml` within the container, then triggers the check, and puts the "Docker image + check result + badge" somewhere safe.
- _Can run commands in a pod's container with `kubectl exec`_
  - `nbtoolbelt` can help running notebooks from CLI: https://gitlab.tue.nl/jupyter-projects/nbtoolbelt/, or [`nbless`](https://github.com/py4ds/nbless), or [`nbscript`](https://github.com/NordicHPC/nbscript)
- _Might JupyterHub be the better component to build CODECHECK on?_
- Can we run a CodecheckersHub instead of JupyterHub, that just starts a pod, runs the image, executes the analysis, executes codecheck (via `kubectl exec`) - _Would BinderHub maintainers welcome this?_
  - CODECHECKHub would be like a read-only JupyterHub? Or just a minimal UI that say "running" and then "check result"?
  - We likely need a BinderHub-level component that can save the container to a file after the check.
- _Does BinderHub keep a list of redirects it makes for users to JupyterHub (so it could execute stuff in user containers) ?_
  - No.
- _How can we export the image to a file and make it available for download? Would that work via a new BinderHub API endpoint?_
- _Is it feasible to run both binder and a binder-fork in the same k8s cluster, using the same Jupyter Hub?_

------

## `codecheck.yml` sketch

```yaml
codecheck_version: 1
input:
  file: "main.ipynb"
  format: "ipython" # default, could also be 'rmarkdown' for Rmd documents, 'python3' for a python script, could be derived from file name
  command: "..." # for rare cases where user needs to define this, but normally should be auto-generated from format
output: # the files that the check uses, if empty, the check generates hashes for all?
  - "model_outputs.csv"
  - "fig1.png"
checks:
  - check_time: "2019-01-01 13:00:00"
    check_runner: "mybinder.org" # who executed the check
    check_signature: "..." # something crpytographic
```
